"""empty message

Revision ID: ffa629fb895f
Revises: 659029851f0a
Create Date: 2021-10-19 15:26:58.723182

"""

# revision identifiers, used by Alembic.
revision = 'ffa629fb895f'
down_revision = '659029851f0a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column('archived_stats', sa.String(length=4096), nullable=True))
    op.add_column('activity', sa.Column('is_archived', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'is_archived')
    op.drop_column('activity', 'archived_stats')
    # ### end Alembic commands ###
