"""empty message

Revision ID: ffa629fb895f
Revises: 
Create Date: 2022-08-26 20:22:03.498886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffa629fb895f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('passcode', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('has_secretary_access', sa.Boolean(), nullable=False),
    sa.Column('archived_stats', sa.String(length=4096), nullable=True),
    sa.Column('age_limit', sa.Integer(), nullable=False),
    sa.Column('stacked_purchases', sa.Boolean(), nullable=False),
    sa.Column('require_terms', sa.Boolean(), nullable=False),
    sa.Column('terms', sa.String(length=4096), nullable=True),
    sa.Column('faq', sa.String(length=4096), nullable=True),
    sa.Column('uuid_prefix', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity')),
    sa.UniqueConstraint('passcode', name=op.f('uq_activity_passcode')),
    mysql_engine='InnoDB'
    )
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cover_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=False),
    sa.Column('bic', sa.String(length=11), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('has_agreed_to_terms', sa.Boolean(), nullable=False),
    sa.Column('barcode', sa.String(length=255), nullable=True),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('fk_participant_activity_id_activity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participant')),
    sa.UniqueConstraint('cover_id', 'activity_id', name=op.f('uq_participant_cover_id')),
    sa.UniqueConstraint('name', 'activity_id', name=op.f('uq_participant_name')),
    mysql_engine='InnoDB'
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('age_limit', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('fk_product_activity_id_activity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product')),
    mysql_engine='InnoDB'
    )
    op.create_table('auction_purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('undone', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('fk_auction_purchase_activity_id_activity')),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], name=op.f('fk_auction_purchase_participant_id_participant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auction_purchase')),
    mysql_engine='InnoDB'
    )
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('undone', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], name=op.f('fk_purchase_activity_id_activity')),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], name=op.f('fk_purchase_participant_id_participant')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_purchase_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase')),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase')
    op.drop_table('auction_purchase')
    op.drop_table('product')
    op.drop_table('participant')
    op.drop_table('activity')
    # ### end Alembic commands ###
